### ISSUE TITLE
Setting sebool container_manage_cgroup

### ISSUE THREAD

**Issue by debianmaster** [debianmaster/openshift-examples#74]
vi roles/openshift_node/tasks/selinux_container_cgroup.yml   
> add when condition

```yaml
# Required in some selinux policy versions see
# https://bugzilla.redhat.com/show_bug.cgi?id=1587825
# https://bugzilla.redhat.com/show_bug.cgi?id=1549765
- name: Setting sebool container_manage_cgroup
  seboolean:
    name: container_manage_cgroup
    state: no
    persistent: yes
  when:
  - ansible_selinux
  - ansible_selinux.status == 'enabled'
```
